### ISSUE TITLE
Handle removal of custom NPCs and items

### ISSUE THREAD

**Issue by desto-git** [desto-git/sdv-mods#5]
https://forums.nexusmods.com/index.php?showtopic=9157378/#entry89205693

It might be problematic if the Gift Decline mod is used with custom NPCs or items after those other mods get removed.

**repro**
1. Add a mod that adds custom NPCs/Items
1. Gift the Item/something to the (new) NPCs
1. Remove the mod again
1. Load the save game

**result**
```
[Gift Decline] This mod failed in the GameLoop.DayEnding event. Technical details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at GiftDecline.NpcHelper.SetGiftTasteLevel(NPC npc, Item item, Int32 desiredGiftTaste)
   at GiftDecline.SaveGameHelper.Apply()
   at GiftDecline.EventHandler.OnDayEnding()
   at GiftDecline.ModEntry.<>c.<Entry>b__1_5(Object sender, DayEndingEventArgs e)
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args, Func`2 match) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\Events\ManagedEvent.cs:line 125
```

**expect**
- No error
- Excess data is skipped (or should it be removed?)

**Comment by desto-git** [comment]
https://forums.nexusmods.com/index.php?showtopic=9157378/#entry97560433

Fixed in 05fb8595d91e03ba53d7daea192c8d0b2846924a
