### ISSUE TITLE
Error "Cannot restore default tastes" when creating a new save

### ISSUE THREAD

**Issue by desto-git** [desto-git/sdv-mods#6]
https://www.nexusmods.com/stardewvalley/mods/6944/?tab=bugs&issue_id=511451

**repro**
1. Add the Gift Decline mod
2. Start the game and create a new save

**result**
```
This mod failed in the GameLoop.DayEnding event. Technical details: System.Exception: Cannot restore default tastes. They are not yet stored.
at GiftDecline.NpcHelper.ResetGiftTastes()
at GiftDecline.SaveGameHelper.ResetSaveState()
at GiftDecline.EventHandler.OnDayEnding()
at GiftDecline.ModEntry.<>c.<Entry>b__1_5(Object sender, DayEndingEventArgs e)
at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args, Func`2 match) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\Events\ManagedEvent.cs:line 125
```

**expect**
- No error

**note**
- It does not seem to affect the functionality of the mod. Gift tastes are still properly reduced.

**Comment by desto-git** [comment]
https://forums.nexusmods.com/index.php?showtopic=9157378/#entry98055393

Fixed in c2287ddfcd8b3348c0bf118bf9b80a9ac944c15e
